{{- if eq .Values.serviceName "service1" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
  - protocol: TCP
    port: {{ .Values.service1.servicePort }}
    targetPort: {{ .Values.service1.containerPort }}
{{- end }}

{{- if eq .Values.serviceName "service2" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
  - protocol: TCP
    port: {{ .Values.service2.servicePort }}
    targetPort: {{ .Values.service2.containerPort }}
{{- end }}
